/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as PostRouteImport } from './routes/post'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MessagesOtherIdRouteImport } from './routes/messages.$otherId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicStripeCheckoutRouteImport } from './routes/api/public/stripe-checkout'

const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesOtherIdRoute = MessagesOtherIdRouteImport.update({
  id: '/messages/$otherId',
  path: '/messages/$otherId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeCheckoutRoute = ApiPublicStripeCheckoutRouteImport.update({
  id: '/api/public/stripe-checkout',
  path: '/api/public/stripe-checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suggestions': typeof SuggestionsRoute
  '/messages/$otherId': typeof MessagesOtherIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/stripe-checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suggestions': typeof SuggestionsRoute
  '/messages/$otherId': typeof MessagesOtherIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages': typeof MessagesIndexRoute
  '/api/public/stripe-checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suggestions': typeof SuggestionsRoute
  '/messages/$otherId': typeof MessagesOtherIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/stripe-checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/post'
    | '/subscriptions'
    | '/suggestions'
    | '/messages/$otherId'
    | '/u/$username'
    | '/messages/'
    | '/api/public/stripe-checkout'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/post'
    | '/subscriptions'
    | '/suggestions'
    | '/messages/$otherId'
    | '/u/$username'
    | '/messages'
    | '/api/public/stripe-checkout'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/post'
    | '/subscriptions'
    | '/suggestions'
    | '/messages/$otherId'
    | '/u/$username'
    | '/messages/'
    | '/api/public/stripe-checkout'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PostRoute: typeof PostRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  MessagesOtherIdRoute: typeof MessagesOtherIdRoute
  UUsernameRoute: typeof UUsernameRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ApiPublicStripeCheckoutRoute: typeof ApiPublicStripeCheckoutRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$otherId': {
      id: '/messages/$otherId'
      path: '/messages/$otherId'
      fullPath: '/messages/$otherId'
      preLoaderRoute: typeof MessagesOtherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-checkout': {
      id: '/api/public/stripe-checkout'
      path: '/api/public/stripe-checkout'
      fullPath: '/api/public/stripe-checkout'
      preLoaderRoute: typeof ApiPublicStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PostRoute: PostRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuggestionsRoute: SuggestionsRoute,
  MessagesOtherIdRoute: MessagesOtherIdRoute,
  UUsernameRoute: UUsernameRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ApiPublicStripeCheckoutRoute: ApiPublicStripeCheckoutRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
